### ISSUE TITLE
Nuget package does not appear to reflect the current src

### ISSUE THREAD

**Issue by srulandhs** [NetDevPack/Security.JwtSigningCredentials#1]
Example

1.

https://github.com/brunohbrito/Jwks.Manager/blob/master/src/Jwks.Manager/SecurityKeyWithPrivate.cs
stamped d13b29b on Feb 26

defines

`
	public JsonWebKey GetSecurityKey()
	{
		return JsonConvert.DeserializeObject<JsonWebKey>(Parameters);
	}
`

but nuget package 3.1.1, dated Monday, February 3, 2020 (2/3/2020)

defines

`
	public SecurityKey GetSecurityKey();
`

2.

Source code indicates Jwks.Manager.Jwks.InMemoryStore is a public class, but it does not appear in the nuget package.

Pulling the latest code, building and checking ildasm confirms.

**Comment by EduardoPires** [comment]
@brunohbrito Can you check this?

**Comment by brunohbrito** [comment]
It's ok now at #10
